### ISSUE TITLE
Document build requirements

### ISSUE THREAD

**Issue by flukejones** [imager-io/imager#1]
This appears to require the nightly rust compiler for successful compilation, along with a C++ compiler, llvm development extras, and clang tooling.

**Comment by colbyn** [comment]
Ahh thanks. I didn’t realize there was a requirement on nightly. It’s been fixed now (67d73e1). The LLVM stuff makes sense, it's a requirement from rust bindgen (used by `vmaf-sys`).

I'll update the README with your information.

**Comment by colbyn** [comment]
Well I've updated the [README](https://github.com/imager-io/imager#building-from-source) (88db954) with requirements for building from source. Should be sufficient for now.

**Comment by colbyn** [comment]
I've finally added prebuilt releases [here](https://github.com/imager-io/imager/releases/tag/system-tools-r1).  The Linux binaries are built from the this [Docker file](https://github.com/imager-io/imager/blob/04765a78a6c81d326361cc9ba82a39c3e7eec335/bin/Dockerfile).

Although there's no Windows support.

**Comment by colbyn** [comment]
Well  for anyone reading, Imager has grown a bit since initial publication. See the new `./README.md` file from this repo for an overview.

Here is table on the rust specific bits:

|Name|Location|Description|
|--|--|--|
|`imager-core`|[imager-io/imager-core](https://github.com/imager-io/imager-core)|Low-Level Implementation|
|`imager-tools`|[imager-io/imager-tools](https://github.com/imager-io/imager-tools)|CLI & Other Executable Tools|

<hr/>

@flukejones I’m afraid I still don’t have a formal file somewhere documenting build requirements. Everything is just changing too fast, and I’m a bit overloaded on such things.

But I’m happy to answer any questions, especially if you want to get involved in the implementation or for using Imager somewhere. Likewise for pull request.

I’m going to close this issue for now. You’re welcome to reopen the issue at [imager-io/imager-core](https://github.com/imager-io/imager-core) or [imager-io/imager-tools](https://github.com/imager-io/imager-tools), whatever is more relevant to you.

**Comment by colbyn** [comment]
Update, there's now documentation at [docs/imager/install.md](https://github.com/imager-io/imager/blob/master/docs/imager/install.md). Feedback is welcome :)
